Fixed database for migrations, added phpmyadmin, added 2 migrations f…
mancopp/project-flow pull request #3
Opened 2024-04-11 16:43 UTC by Remus337

…or Tasks and Statuses, Made first application logic with CRUD, more in the task (Trello)

2024-04-17 06:37 UTC, mancopp requested changes
Minor adjustments and code fixes

2024-04-17 06:37 UTC, mancopp commented on src/Controller/TaskController.php
> +            'form' => $form->createView(),
Produces RuntimeError, because as of now twig requires parameter "tasks"

2024-04-17 06:37 UTC, mancopp commented on src/Controller/TaskController.php
> +    #[Route('/tasks/{id}/delete', name: 'task_delete', methods: ['POST'])]
This route does not work.

2024-04-17 06:37 UTC, mancopp commented on src/Repository/StatusRepository.php
> +class StatusRepository extends ServiceEntityRepository
Commented snippets are safe to remove, I assume?

2024-04-18 15:39 UTC, Remus337 reviewed
Done

2024-04-18 15:40 UTC, mancopp approved these changes
LGTM

2024-04-18 15:40 UTC, merged